import puppeteer from 'puppeteer-core'
import { mkdirSync } from 'node:fs'
const EXE='C:/Program Files/Google/Chrome/Application/chrome.exe'
const URL='http://localhost:5182/'
const OUT='C:/Users/Erstr/OneDrive/Bureaublad/swoobz-games-export/swoobz-games-export/assay-run/autisk-dehaze-0706'
mkdirSync(OUT,{recursive:true})
const wait=ms=>new Promise(r=>setTimeout(r,ms))
const clickText=(page,rs)=>page.evaluate((rs)=>{const r=new RegExp(rs,'i');const b=[...document.querySelectorAll('button,div,span')].find(x=>r.test((x.textContent||'').trim())&&(x.tagName==='BUTTON'||getComputedStyle(x).cursor==='pointer'));if(b){b.click();return true}return false},rs)
const dismiss=(page)=>page.evaluate(()=>{const x=[...document.querySelectorAll('button,div,span')].find(e=>(e.textContent||'').trim()==='×'||e.getAttribute?.('aria-label')==='close');if(x){x.click();return true}return false})
async function traceLine(page,n){const geo=await page.evaluate(()=>{const c=document.querySelector('canvas');const r=c.getBoundingClientRect();return{left:r.left,top:r.top,w:r.width}});const TILE=geo.w/14;const cells=[];for(let row=3;row<=9&&cells.length<n;row++){const cols=row%2?[3,4,5,6,7,8]:[8,7,6,5,4,3];for(const col of cols){if(cells.length<n)cells.push([col,row])}}for(const[col,row]of cells){await page.mouse.click(geo.left+col*TILE+TILE/2,geo.top+row*TILE+TILE/2);await wait(45)}return geo}
async function headerCrop(page,path){const rect=await page.evaluate(()=>{const el=[...document.querySelectorAll('div')].find(d=>/TO WIN/i.test(d.textContent||'')&&d.getBoundingClientRect().width<640&&d.getBoundingClientRect().width>150&&d.getBoundingClientRect().height<160);if(!el)return null;const r=el.getBoundingClientRect();return{x:Math.max(0,r.x-6),y:Math.max(0,r.y-6),width:Math.min(r.width+12,720),height:r.height+12}});if(rect)await page.screenshot({path,clip:rect});return rect}
const browser=await puppeteer.launch({executablePath:EXE,headless:false,defaultViewport:null,args:['--autoplay-policy=no-user-gesture-required','--window-size=1500,1050']})
// DESKTOP armed hero
{const page=await browser.newPage();await page.setViewport({width:1440,height:900,deviceScaleFactor:1});await page.goto(URL,{waitUntil:'load'});await wait(1300);await clickText(page,'ENTER THE DIVE');await wait(600);await dismiss(page);await wait(300);await traceLine(page,12);await wait(500);const r=await headerCrop(page,`${OUT}/D-hero-armed.png`);console.log('D armed hero rect',JSON.stringify(r));
 // measure overflow of hero container children
 const ov=await page.evaluate(()=>{const el=[...document.querySelectorAll('div')].find(d=>/TO WIN/i.test(d.textContent||'')&&d.getBoundingClientRect().width<640&&d.getBoundingClientRect().width>150&&d.getBoundingClientRect().height<160);if(!el)return null;const r=el.getBoundingClientRect();return{scrollW:el.scrollWidth,clientW:el.clientWidth,overflow:el.scrollWidth>el.clientWidth+1}});console.log('D hero overflow',JSON.stringify(ov));await page.close()}
// MOBILE armed hero
{const page=await browser.newPage();await page.setViewport({width:412,height:915,deviceScaleFactor:3,isMobile:true,hasTouch:true});await page.goto(URL,{waitUntil:'load'});await wait(1300);await clickText(page,'ENTER THE DIVE');await wait(600);await dismiss(page);await wait(300);await traceLine(page,18);await wait(500);const r=await headerCrop(page,`${OUT}/M-hero-armed.png`);console.log('M armed hero rect',JSON.stringify(r));const ov=await page.evaluate(()=>{const el=[...document.querySelectorAll('div')].find(d=>/TO WIN/i.test(d.textContent||'')&&d.getBoundingClientRect().width<640&&d.getBoundingClientRect().width>150&&d.getBoundingClientRect().height<200);if(!el)return null;return{scrollW:el.scrollWidth,clientW:el.clientWidth,overflow:el.scrollWidth>el.clientWidth+1}});console.log('M hero overflow',JSON.stringify(ov));await page.close()}
await browser.close();console.log('DONE')
