import puppeteer from 'puppeteer-core';
const EXE='C:/Program Files/Google/Chrome/Application/chrome.exe';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await puppeteer.launch({executablePath:EXE,headless:false,defaultViewport:{width:1920,height:1080,deviceScaleFactor:1},args:['--window-size=1940,1220']});
const page=(await browser.pages())[0];
await page.goto('http://localhost:5181/',{waitUntil:'networkidle2',timeout:60000});
await wait(1200);
const f = await page.evaluate(()=>getComputedStyle(document.body).fontFamily);
console.log('FONT:', f);
await browser.close();
