import puppeteer from 'puppeteer-core';
const EXE='C:/Program Files/Google/Chrome/Application/chrome.exe';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const [PORT,W,H,TAG] = [process.argv[2]||'5181', parseInt(process.argv[3]||'1920'), parseInt(process.argv[4]||'1080'), process.argv[5]||'D1920'];
const browser=await puppeteer.launch({executablePath:EXE,headless:false,defaultViewport:{width:W,height:H,deviceScaleFactor:1},args:[`--window-size=${W+20},${H+140}`,'--autoplay-policy=no-user-gesture-required']});
const page=(await browser.pages())[0];
await page.goto(`http://localhost:${PORT}/`,{waitUntil:'networkidle2',timeout:60000});
await wait(1500);
const m = await page.evaluate(() => {
  const board = document.querySelector('[data-testid="vault-canvas-shell"]');
  const cabinet = board.parentElement;
  const pageDiv = cabinet.parentElement;
  const kids = [...pageDiv.children].filter(k=>k.tagName==='DIV');
  const first = kids[0].getBoundingClientRect();
  const last = kids[kids.length-1].getBoundingClientRect();
  const cabRect = cabinet.getBoundingClientRect();
  const vw = window.innerWidth, vh = window.innerHeight;
  return { vw, vh, contentTop:first.top, contentBottom:last.bottom, cabW:cabRect.width, cabH:cabRect.height };
});
const contentH = m.contentBottom - m.contentTop;
const deadTotal = m.vh - contentH;
const deadPct = (deadTotal / m.vh * 100).toFixed(1);
console.log(TAG, JSON.stringify(m));
console.log(TAG, 'contentH:', contentH.toFixed(1), ' TOTAL DEAD px:', deadTotal.toFixed(1), ' pct of vh:', deadPct+'%');
console.log(TAG, 'top void px:', m.contentTop.toFixed(1), '  bottom void px:', (m.vh-m.contentBottom).toFixed(1));
console.log(TAG, 'cabinet WxH:', m.cabW.toFixed(0)+'x'+m.cabH.toFixed(0), ' width fill pct of vw:', (m.cabW/m.vw*100).toFixed(1)+'%');
await browser.close();
